import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { FC } from "react";
import Link from "next/link";
import Hoc from "@/components/Hoc";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dream Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* TODO: Add favicon */}
        <link rel="icon" href="/favi-con.png" />
      </Head>
      <Hoc>
        <div className=" w-full  xs:h-[80%] mt-10 p-10 flex justify-center lg:flex-row xs:flex-col gap-3">
          <MainBtn text="Search" style="btn-primary " link="search" />
          <MainBtn text="Register" style="btn-secondary " link="register" />
          <MainBtn text="Lease" style="btn-accent " link="lease" />
        </div>
      </Hoc>
    </>
  );
}

const MainBtn: FC<{ text: string; style: string; link: string }> = ({
  text,
  style,
  link,
}) => (
  <Link
    className={`${style} lg:w-[30%]  xs:w-full h-[30%] rounded-md btn text-2xl`}
    href={`/${link}`}
  >
    {text}
  </Link>
);
